import { SurveySubmission } from "@/lib/types";

export interface IndicatorMeta {
  id: number;
  numberStr: string;
  title: string;
  shortDesc: string;
  fullDesc: string;
  requiredProof: string;
  focusHint: string;
  bobotNilai: number; // Bobot: Partisipasi=1, SDM=2, Event/Prestasi=3
  tingkatWilayah: "Kabupaten/Kota" | "Provinsi"; // Tingkat wilayah indikator
  keteranganInklusif?: string; // Keterangan inklusivitas penyandang disabilitas
}

export const SURVEY_INDICATORS: IndicatorMeta[] = [
  {
    id: 1,
    numberStr: "Indikator 1",
    title: "Kejuaraan Pelajar Tingkat Nasional dan Internasional",
    shortDesc: "Keikutsertaan kontingen pelajar (SD/SMP/SMA/SMK) yang menghasilkan prestasi medali.",
    fullDesc: "Seluruh kejuaraan atau kompetisi olahraga resmi yang diperuntukkan bagi peserta didik dari jenjang SD s/d SMA/SMK sederajat pada tingkat nasional maupun internasional yang menghasilkan medali.",
    requiredProof: "Surat Penugasan Resmi, Hasil Pertandingan Resmi, Sertifikat, atau Piagam Medali (PDF).",
    focusHint: "Hanya laporkan kejuaraan yang menghasilkan perolehan medali Emas, Perak, atau Perunggu.",
    bobotNilai: 3,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Termasuk pelajar penyandang disabilitas yang berprestasi dalam kejuaraan ini.",
  },
  {
    id: 2,
    numberStr: "Indikator 2",
    title: "Peningkatan Mutu SDM Olahraga (Pelatih/Wasit/Juri)",
    shortDesc: "Pendidikan, pelatihan, penataran, atau sertifikasi lisensi nasional/internasional.",
    fullDesc: "Kegiatan peningkatan kompetensi teknis pelatih, wasit, atau juri yang diselenggarakan oleh kementerian, induk cabang olahraga, atau lembaga resmi pada tahun pelaporan.",
    requiredProof: "Sertifikat Kelulusan Resmi, SK Kelulusan Lisensi, atau Piagam Sertifikasi (PDF).",
    focusHint: "Data harus membuktikan peserta telah lulus dan dinyatakan memperoleh lisensi kompetensi.",
    bobotNilai: 2,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Termasuk pelatih/wasit/juri penyandang disabilitas yang memperoleh sertifikasi dan lisensi.",
  },
  {
    id: 3,
    numberStr: "Indikator 3",
    title: "Pelatih Cabor Membawa Tim Tingkat Nasional & Internasional",
    shortDesc: "Pelatih domisili daerah yang mendapat penugasan resmi mendampingi kontingen.",
    fullDesc: "Pelatih yang berdomisili atau tercatat berasal dari kabupaten/kota serta memperoleh penugasan resmi dari induk cabor atau instansi pemerintah untuk memimpin tim.",
    requiredProof: "Surat Keputusan (SK) Penugasan Resmi atau Daftar Kontingen Terverifikasi (PDF).",
    focusHint: "Lampirkan bukti SK penugasan resmi dari instansi pemerintah atau Pengprov/PB Cabor.",
    bobotNilai: 2,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Termasuk pelatih yang mendampingi tim paralimpik atau tim inklusif penyandang disabilitas.",
  },
  {
    id: 4,
    numberStr: "Indikator 4",
    title: "Wasit Cabang Olahraga Masuk dalam Wasit Nasional & Internasional",
    shortDesc: "Wasit daerah yang memiliki lisensi dan pengakuan aktif tingkat nasional/internasional.",
    fullDesc: "Wasit yang berasal dari kabupaten/kota dan memiliki pengakuan resmi serta sertifikasi aktif untuk memimpin kejuaraan tingkat nasional atau internasional sesuai regulasi cabor.",
    requiredProof: "Buku Lisensi Resmi, Kartu Tanda Wasit Nasional, atau Sertifikat Penetapan (PDF).",
    focusHint: "Pastikan masa berlaku lisensi wasit masih aktif pada tahun pelaporan berjalan.",
    bobotNilai: 2,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Termasuk wasit penyandang disabilitas yang memiliki lisensi aktif dan diakui secara resmi.",
  },
  {
    id: 5,
    numberStr: "Indikator 5",
    title: "Wasit/Juri yang Bertugas pada Kegiatan Nasional & Internasional",
    shortDesc: "Penugasan aktif memimpin atau menilai jalannya pertandingan kejuaraan resmi.",
    fullDesc: "Wasit dan/atau juri yang secara faktual bertugas di arena kejuaraan nasional/internasional berdasarkan surat mandat resmi dari lembaga berwenang.",
    requiredProof: "Surat Tugas Resmi / Surat Mandat Pertandingan dari PB/PP Cabor atau Panpel (PDF).",
    focusHint: "Cantumkan nama event kejuaraan dan nomor surat tugas penugasan lapangan.",
    bobotNilai: 2,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Termasuk wasit/juri penyandang disabilitas yang ditugaskan secara resmi pada kegiatan nasional/internasional.",
  },
  {
    id: 6,
    numberStr: "Indikator 6",
    title: "Atlet Cabang Olahraga Mewakili Tim Nasional & Internasional",
    shortDesc: "Atlet daerah yang resmi memperkuat tim kontingen provinsi atau Indonesia.",
    fullDesc: "Atlet binaan kabupaten/kota yang ditetapkan melalui SK resmi sebagai anggota tim atau kontingen mewakili daerah, provinsi, atau Tim Nasional Indonesia.",
    requiredProof: "SK Penetapan Atlet Kontingen, Surat Pemanggilan Pelatnas/Pelatda, ID Card Event (PDF).",
    focusHint: "Sebutkan nama atlet, nomor pertandingan cabor, dan capaian pada kejuaraan tersebut.",
    bobotNilai: 3,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Termasuk atlet penyandang disabilitas yang mewakili tim kontingen paralimpik atau tim inklusif.",
  },
  {
    id: 7,
    numberStr: "Indikator 7",
    title: "Penyelenggaraan Event Olahraga Nasional & Internasional",
    shortDesc: "Kejuaraan skala nasional/internasional yang diselenggarakan di wilayah daerah.",
    fullDesc: "Event olahraga bergengsi yang sukses digelar di wilayah kabupaten/kota oleh pemerintah daerah atau mitra swasta dengan partisipasi peserta lintas provinsi/negara.",
    requiredProof: "Buku Laporan Pertanggungjawaban (LPJ) Event, SK Tuan Rumah, atau Dokumentasi Resmi (PDF).",
    focusHint: "Sebutkan jumlah provinsi/kontingen peserta yang hadir di wilayah Anda.",
    bobotNilai: 3,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Event harus menyelenggarakan venue dan fasilitas yang aksesibel bagi peserta penyandang disabilitas.",
  },
  {
    id: 8,
    numberStr: "Indikator 8",
    title: "Prestasi Event Olahraga Masyarakat Tingkat Nasional",
    shortDesc: "Capaian dalam olahraga kebugaran, rekreasi, dan pelestarian budaya olahraga.",
    fullDesc: "Capaian daerah dalam penyelenggaraan maupun partisipasi pada festival/kejuaraan olahraga masyarakat (KORMI) yang berorientasi kebugaran dan kebersamaan.",
    requiredProof: "Piagam Partisipasi Resmi, Berita Acara Kegiatan, atau Laporan Kontingen (PDF).",
    focusHint: "Olahraga rekreasi masyarakat berbeda dengan olahraga prestasi; fokus pada partisipasi komunitas.",
    bobotNilai: 1,
    tingkatWilayah: "Kabupaten/Kota",
    keteranganInklusif: "Event harus membuka partisipasi bagi masyarakat penyandang disabilitas dan kelompok rentan lainnya.",
  },
  // Indikator Tingkat Provinsi
  {
    id: 9,
    numberStr: "Indikator Provinsi 1",
    title: "Prestasi Atlet Tingkat Provinsi",
    shortDesc: "Atlet provinsi yang meraih medali pada kejuaraan tingkat nasional/internasional.",
    fullDesc: "Atlet yang mewakili provinsi dan berhasil meraih medali pada kejuaraan tingkat nasional atau internasional sebagai bentuk prestasi tingkat provinsi.",
    requiredProof: "SK Kontingen, Piagam Medali, Sertifikat Resmi (PDF).",
    focusHint: "Laporkan prestasi atlet provinsi yang meraih medali Emas, Perak, atau Perunggu.",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Termasuk atlet penyandang disabilitas dari provinsi yang meraih medali paralimpik.",
  },
  {
    id: 10,
    numberStr: "Indikator Provinsi 2",
    title: "SDM Olahraga Bersertifikat Tingkat Provinsi",
    shortDesc: "Pelatih/Wasit/Juri provinsi dengan sertifikasi internasional atau lisensi elite.",
    fullDesc: "Tenaga SDM olahraga tingkat provinsi (pelatih, wasit, juri) yang memperoleh sertifikasi internasional atau lisensi elite dari federasi internasional.",
    requiredProof: "Sertifikat Internasional, Lisensi Elite, Surat Pengakuan Federasi (PDF).",
    focusHint: "Pastikan sertifikat masih berlaku dan diakui oleh federasi internasional pada tahun pelaporan.",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Termasuk SDM penyandang disabilitas yang memperoleh sertifikasi internasional.",
  },
  {
    id: 11,
    numberStr: "Indikator Provinsi 3",
    title: "Event Olahraga Bergengsi Tingkat Nasional/Internasional",
    shortDesc: "Event olahraga berskala nasional/internasional diselenggarakan di provinsi.",
    fullDesc: "Kejuaraan olahraga bergengsi tingkat nasional atau internasional yang sukses diselenggarakan di wilayah provinsi dengan peserta lintas provinsi/negara.",
    requiredProof: "LPJ Event, SK Tuan Rumah, Dokumentasi Kehadiran Peserta (PDF).",
    focusHint: "Sebutkan nama event, jumlah provinsi peserta, dan tingkat (nasional/internasional).",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Event harus memastikan aksesibilitas penuh untuk peserta dan penonton penyandang disabilitas.",
  },
  {
    id: 12,
    numberStr: "Indikator Provinsi 4",
    title: "Pelatih Provinsi di Tim Nasional/Internasional",
    shortDesc: "Pelatih provinsi yang ditugaskan memimpin tim nasional atau kontingen internasional.",
    fullDesc: "Pelatih binaan provinsi yang mendapat penugasan resmi dari kemenpora atau induk cabor untuk memimpin tim nasional atau kontingen pada kejuaraan internasional.",
    requiredProof: "SK Penugasan Resmi, Surat Mandat Tim Nasional (PDF).",
    focusHint: "Lampirkan bukti SK penugasan dan nama tim/event yang dipimpin.",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Termasuk pelatih penyandang disabilitas yang ditugaskan di tim nasional/internasional.",
  },
  {
    id: 13,
    numberStr: "Indikator Provinsi 5",
    title: "Wasit/Juri Provinsi di Kejuaraan Internasional",
    shortDesc: "Wasit/Juri provinsi yang ditugaskan di kejuaraan tingkat internasional.",
    fullDesc: "Wasit atau juri dari provinsi yang ditugaskan secara resmi untuk memimpin/menilai pada kejuaraan internasional berdasarkan surat mandat lembaga berwenang.",
    requiredProof: "Surat Mandat Internasional, Kredensial Pertandingan (PDF).",
    focusHint: "Lampirkan bukti penugasan di kejuaraan internasional dengan tanggal event.",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Termasuk wasit/juri penyandang disabilitas yang ditugaskan internasional.",
  },
  {
    id: 14,
    numberStr: "Indikator Provinsi 6",
    title: "Program Pembinaan Atlet Elite Provinsi",
    shortDesc: "Program terstruktur pembinaan atlet elite tingkat provinsi dengan target medali.",
    fullDesc: "Program pembinaan atlet yang terstruktur dan berkelanjutan dengan target meraih medali di kejuaraan nasional/internasional, dengan dukungan fasilitas dan pendanaan provinsi.",
    requiredProof: "Dokumentasi Program Pembinaan, Daftar Atlet Binaan, Laporan Capaian (PDF).",
    focusHint: "Jelaskan target prestasi, durasi program, dan jumlah atlet yang dibina.",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Program pembinaan harus membuka kesempatan bagi atlet penyandang disabilitas.",
  },
  {
    id: 15,
    numberStr: "Indikator Provinsi 7",
    title: "Infrastruktur Olahraga Standar Nasional/Internasional",
    shortDesc: "Fasilitas olahraga provinsi dengan standar nasional/internasional yang digunakan untuk kompetisi.",
    fullDesc: "Fasilitas olahraga di provinsi yang telah memenuhi standar nasional atau internasional (berstandar ISO, akreditasi FPOI, atau sertifikasi lainnya) dan digunakan untuk menyelenggarakan kompetisi.",
    requiredProof: "Sertifikat Standar Fasilitas, Laporan Audit, Dokumentasi Fasilitas (PDF).",
    focusHint: "Sebutkan nama fasilitas, jenis olahraga, dan standar yang dipenuhi.",
    bobotNilai: 3,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Fasilitas harus aksesibel dan ramah bagi penyandang disabilitas sesuai standar internasional.",
  },
  {
    id: 16,
    numberStr: "Indikator Provinsi 8",
    title: "Program Pemberdayaan Olahraga Masyarakat Provinsi",
    shortDesc: "Program olahraga masyarakat yang inklusif dan berkelanjutan di tingkat provinsi.",
    fullDesc: "Program olahraga rekreasi, kebugaran, atau budaya olahraga yang diselenggarakan provinsi secara berkelanjutan, inklusif, dan melibatkan masyarakat luas termasuk kelompok rentan.",
    requiredProof: "Laporan Program, Dokumentasi Kegiatan, Daftar Peserta (PDF).",
    focusHint: "Jelaskan frekuensi, jangkauan peserta, dan dampak bagi masyarakat.",
    bobotNilai: 1,
    tingkatWilayah: "Provinsi",
    keteranganInklusif: "Program harus membuka partisipasi penuh bagi penyandang disabilitas dan kelompok rentan lainnya.",
  },
];

export const INITIAL_SUBMISSIONS: SurveySubmission[] = [
  {
    id: "SRV-2024-001",
    createdAt: "2024-05-20T10:30:00Z",
    tahunSurvei: 2024,
    responden: {
      namaLengkap: "Bambang Pamungkas, S.Pd.",
      umur: 38,
      jenisKelamin: "Laki-laki",
      kabupatenKota: "Kabupaten Kutai Kartanegara",
      kecamatan: "Tenggarong",
      pekerjaan: "Pengurus Cabang Olahraga Atletik",
      nomorTelepon: "0812-3456-7890",
    },
    answers: {
      1: {
        indicatorId: 1,
        indicatorTitle: "Kejuaraan Pelajar Tingkat Nasional dan Internasional",
        namaKegiatan: "Kejuaraan Nasional Atletik Pelajar U-18",
        cabangOlahraga: "Atletik (Lari 100m & Lompat Jauh)",
        tingkatPenyelenggaraan: "Nasional",
        sumberPendanaan: "APBD",
        capaianPrestasi: "1 Emas (Lari 100m Putra) dan 1 Perak (Lompat Jauh Putri)",
        medaliEmas: 1,
        medaliPerak: 1,
        medaliPerunggu: 0,
        jumlahPeserta: 12,
        uraianKegiatan: "Kontingen pelajar Kutai Kartanegara berhasil meraih 1 emas dan 1 perak dalam Kejurnas Atletik Pelajar di Jakarta.",
        fileBuktiName: "SK_Kontingen_Kejurnas_Pelajar_2024.pdf",
        fileBuktiSize: "2.4 MB",
        fileBuktiHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      },
    },
    status: "TERVERIFIKASI",
    catatanVerifikator: "Dokumen SK dan piagam sah telah diverifikasi oleh Tim Dispora.",
    totalIndikatorTerisi: 8,
  },
  {
    id: "SRV-2024-002",
    createdAt: "2024-05-24T14:15:00Z",
    tahunSurvei: 2024,
    responden: {
      namaLengkap: "Dewi Sartika, M.Or.",
      umur: 32,
      jenisKelamin: "Perempuan",
      kabupatenKota: "Kota Balikpapan",
      kecamatan: "Balikpapan Barat",
      pekerjaan: "Pelatih Renang Tingkat Daerah",
      nomorTelepon: "0813-9876-5432",
    },
    answers: {
      2: {
        indicatorId: 2,
        indicatorTitle: "Peningkatan Mutu SDM Olahraga (Pelatih/Wasit/Juri)",
        namaKegiatan: "Sertifikasi Pelatih Renang Nasional Level 2 PB PRSI",
        cabangOlahraga: "Akuatik / Renang",
        tingkatPenyelenggaraan: "Nasional",
        sumberPendanaan: "Swasta/Sponsorship",
        capaianPrestasi: "Lulus Ujian Kompetensi dengan Lisensi B Nasional",
        uraianKegiatan: "Mengikuti penataran dan ujian sertifikasi lisensi nasional selama 5 hari di Jakarta.",
        fileBuktiName: "Sertifikat_Pelatih_Nasional_DewiSartika.pdf",
        fileBuktiSize: "1.8 MB",
        fileBuktiHash: "d7a8fbb307d7809469ca9abcb0082e4f8d5651e46d3cdb762d02d0bf37c9e592",
      },
    },
    status: "TERKIRIM",
    catatanVerifikator: "Menunggu pemeriksaan fisik berkas oleh Verifikator Bidang Olahraga Prestasi.",
    totalIndikatorTerisi: 6,
  },
];
